language: python
python:
  - "3.7"
  - "3.8"

before_install:
  - pip install -U pip
  - sudo apt-get install libgnutls28-dev
  - python setup.py install
  - pip install -e .

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pep8
  - pip install pep8-naming
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

# command to run tests
script:
  - flake8 src
  - pytest

after_success:
  - pytest --cov=src tests
  - codecov
